name: ecommerce
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpe
     - assets/flasha.jpg
     - assets/flashdrive.jpg
     - assets/flasha2.jpg
     - assets/flasha3.jpg
     - assets/flasha4.jpg
     - assets/flasha5.jpg
     - assets/flasha6.jpg
     - assets/flasha7.jpg
     - assets/flasha8.jpg
     - assets/supermarket.jpeg
     - assets/makeup_cover.jpeg
     - assets/house_cleaning.jpeg
     - assets/pasta&rice.jpeg
     - assets/dipers&wipes.jpeg
     - assets/gillette.jpeg
     - assets/food.jpeg
     - assets/deodorants.jpeg
     - assets/deverages.jpeg
     - assets/beautytools.jpeg
     - assets/Armafood.jpeg
     - assets/carseats.jpeg
     - assets/haircares.jpeg
     - assets/luxurybeauty.jpeg
     - assets/laundary&detergents.jpeg
     - assets/Abu Auf.jpeg
     - assets/Soaps&bodywash.jpeg
     - assets/Electeric personal cares.jpeg
     - assets/mskara.jpeg
     - assets/souq.jpeg
     - assets/Maybelline.jpeg
     - assets/boder.jpeg
     - assets/fawndation.jpeg
     - assets/liquidroj.jpeg
     - assets/for4a.jpeg
     - assets/Mob1.jpeg
     - assets/Mob2.jpeg
     - assets/Mob3.jpeg
     - assets/Mob4.jpeg
     - assets/Mob5.jpeg
     - assets/Mob6.jpeg
     - assets/Mob7.jpeg
     - assets/Mob8.jpeg
     - assets/Mob9.jpeg
     - assets/Mob10.jpeg
     - assets/Mob11.jpeg
     - assets/Mob12.jpeg
     - assets/Mob13.jpeg
     - assets/Mob14.jpeg
     - assets/Mob15.jpeg
     - assets/Accessories.jpeg
     - assets/PowerBanks.jpeg
     - assets/Chargers.jpeg
     - assets/Headsets.jpeg
     - assets/MemoryCards.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
